imaps:
  host: "imap.gmail.com"
  port: "993"
  user: "email.test.mulesoft@gmail.com"
  password: "${secure::imaps.password}"
  
smtp:
  host: "smtp.gmail.com"
  port: "587"
  user: "email.test.mulesoft@gmail.com"
  password: "${secure::smtp.password}"